name: ci
on: [push]
jobs:
  test:
    uses: cypress-io/github-action@v2
    with:
      # build: npm run build
      start: npm run dev
      wait-on: 'http://localhost:5173'
      # browser: chrome
      # record: true
      # parallel: true
      # group: 'Rick and Morty'
      # tag: 'main'
      # spec: 'cypress/integration/rick-and-morty.spec.js'
