name: Cypress Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start Application and Wait
        run: npm run dev &
          sleep 10
          npx wait-on 'http://127.0.0.1:5173/' --timeout 120000

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: 'http://127.0.0.1:5173/'
          wait-on-timeout: 120
