name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Start Vite server
        run: npm run dev &

      - name: Run Cypress tests and Generate Mochawesome Report
        id: cypress
        run: |
          npx cypress run --config baseUrl=http://localhost:5173 || true
          echo "CYPRESS_EXIT_STATUS=$?" >> $GITHUB_ENV

          # Generate HTML report from JSON
          #npx merge cypress/reports/mochawesome.json -f report -o reports

          # List cypress/reports folder (for debugging)
          ls cypress/reports

      - name: Read Test Pass/Fail Count from Mochawesome Report (using jq)
        id: read_test_data
        if: always()
        run: |
          test_summary=$(jq '.stats | .passes, .failures' cypress/reports/mochawesome.json)
          echo "Test Summary: $test_summary" 
          echo "Test Failed: $test_fail_count"
          echo "Test Passed: $test_pass_count"
          # Set job outputs
          echo "::set-output name=TEST_PASS_COUNT::$(jq '.results[0].suites[0].passes | length' cypress/reports/mochawesome.json)"
          echo "::set-output name=TEST_FAIL_COUNT::$(jq '.results[0].suites[0].failures | length' cypress/reports/mochawesome.json)"

      - name: Make a post request using curl
        if: always()
        run: |
          # curl -X POST -H "Content-Type: application/json" -d @cypress/reports/mochawesome.json https://json-reciver-759273bf5919.herokuapp.com/receive

          curl -X POST -H "Content-Type: application/json" -d @cypress/reports/mochawesome.json https://3rksbp2k-3000.inc1.devtunnels.ms/receive

      - name: Send Email with Data
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: 'smtp-mail.outlook.com'
          server_port: 587
          username: 'githubreport@outlook.com'
          password: "'kq'x;u@!n94'sg6W8T`"
          subject: 'Cypress Test Report ( Failed: ${{ steps.read_test_data.outputs.TEST_FAIL_COUNT }})'
          from: 'githubreport@outlook.com'
          to: 'ariful.rony10@gmail.com'
          html_body: |
            <!DOCTYPE html>
            <html lang="en">
              <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Document</title>
                <style>
                  table {
                    font-family: arial, sans-serif;
                    border-collapse: collapse;
                    width: 100%;
                    border-radius: 20px;
                  }

                  td,
                  th {
                    border: 1px solid #dddddd;
                    text-align: left;
                    padding: 8px;
                    text-align: center;
                    font-weight: 700;
                  }

                  tr:nth-child(even) {
                    background-color: #dddddd;
                  }
                </style>
              </head>
              <body style="background-color: red">
                <div
                  style="
                    background-color: white;
                    border-radius: 10px;
                    margin: 10px;
                    padding: 10px;
                  "
                >
                  <header style="text-align: center">
                    <img
                      src="https://i.ibb.co/8NgwwbN/order-monkey-logo.png"
                      alt="Order Monkey Logo"
                    />
                  </header>
                  <main style="text-align: center">
                    <h2>Cypress Test Report</h2>
                    <h3>Total Test Run: <span style="font-weight: 700"></span></h3>
                    <table>
                      <tr>
                        <th style="background-color: rgb(152, 253, 152)">Passed</th>
                        <th style="background-color: rgb(255, 135, 135)">Failed</th>
                      </tr>
                      <tr>
                        <td>2</td>
                        <td>5</td>
                      </tr>
                    </table>
                    <p>For more details please visit: ${{github.repository}}</p>
                  </main>
                </div>
              </body>
            </html>

          attachments: 'cypress/reports/mochawesome.json'
