name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Start Vite server
        run: npm run dev &

      - name: Run Cypress tests
        run: npm run test:cypress -- --exit || echo "Cypress tests failed with exit code $?"

      # - name: Generate Mochawesome Report
      #   run: npx cypress run --config baseUrl=http://localhost:5173

      - name: Archive Mochawesome Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports

      # - name: Send Email with Mochawesome Report
      #   uses: dawidd6/action-send-mail@v2
      #   with:
      #     server_address: 'smtp.gmail.com'
      #     server_port: 587
      #     username: 'reportcypress'
      #     password: 'K8NbZegNxtYnuLcEAoi9'
      #     subject: 'Cypress Test Report'
      #     from: 'reportcypress@gmail.com'
      #     to: 'ariful.rony10@gmail.com'
      #     body: 'Please find the attached Mochawesome test report.'
      #     attachments: 'cypress/reports/mochawesome-report/mochawesome.json'
      #     content_type: 'text/plain'
      - name: Send Email with Mochawesome Report
        run: |
          npm install nodemailer
          node -e "const nodemailer = require('nodemailer'); const transporter = nodemailer.createTransport({ host: 'smtp.example.com', port: 587, auth: { user: '$EMAIL_USERNAME', pass: '$EMAIL_PASSWORD' } }); transporter.sendMail({ from: 'your-email@example.com', to: 'recipient-email@example.com', subject: 'Cypress Test Report', text: 'Please find the attached Mochawesome test report.', attachments: [{ path: 'cypress/reports/mochawesome-report/mochawesome.json' }] }, (error, info) => { if (error) { console.error(error); } else { console.log('Email sent: ' + info.response); } });"
        env:
          EMAIL_USERNAME: 'reportcypress@gmail.com'
          EMAIL_PASSWORD: 'K8NbZegNxtYnuLcEAoi9'
