name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Start Vite server
        run: npm run dev &

      - name: Run Cypress tests
        run: npm run test:cypress

      - name: Handle Cypress Test Failure
        if: failure()
        run: |
          echo "Cypress tests failed. Continuing to generate report."

          # Generate Mochawesome Report
          npx cypress run --config baseUrl=http://localhost:5173

          # Generate Report Status
          if [ $? -eq 0 ]; then
            echo "Test Report Status: Passed"
          else
            echo "Test Report Status: Failed"
          fi
          export REPORT_STATUS=$(echo)

          # Send Email with Mochawesome Report
          echo "Sending email with report..."

          uses: dawidd6/action-send-mail@v2 # Assuming the action uses snake_case for outputs
          with:
            server_address: 'smtp-mail.outlook.com'
            server_port: 587
            username: 'githubreport@outlook.com'
            password: "'kq'x;u@!n94'sg6W8T`"
            subject: 'Cypress Test Report (${REPORT_STATUS})' # Use REPORT_STATUS output
            from: 'githubreport@outlook.com'
            to: 'ariful.rony10@gmail.com'
            body: |
              Please find the attached Mochawesome test report.

              Test results: ${{ steps.Generate_Report_Status.outputs.REPORT_STATUS }}
            attachments: 'mochawesome-report/mochawesome.json'
            content_type: 'text/plain'

      - name: Generate Mochawesome Report
        run: npx cypress run --config baseUrl=http://localhost:5173

      - name: Generate Report Status
        run: |
          if [ $? -eq 0 ]; then
            echo "Test Report Status: Passed"
          else
            echo "Test Report Status: Failed"
          fi
          export REPORT_STATUS=$(echo)  # Capture output for conditional use

      - name: Send Email with Mochawesome Report
        uses: dawidd6/action-send-mail@v2 # Assuming the action uses snake_case for outputs
        with:
          server_address: 'smtp-mail.outlook.com'
          server_port: 587
          username: 'githubreport@outlook.com'
          password: "'kq'x;u@!n94'sg6W8T`"
          subject: 'Cypress Test Report (${REPORT_STATUS})' # Use REPORT_STATUS output
          from: 'githubreport@outlook.com'
          to: 'ariful.rony10@gmail.com'
          body: |
            Please find the attached Mochawesome test report.

            Test results: ${{ steps.Generate_Report_Status.outputs.REPORT_STATUS }}
          attachments: 'mochawesome-report/mochawesome.json'
          content_type: 'text/plain'

      - name: Exit Code
        run: exit 0 # Set exit code to 0 to allow workflow continuation


      # Optional: Archive Mochawesome Report (consider security implications)
      # - name: Archive Mochawesome Report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: mochawesome-report
      #     path: cypress/
