name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Start Vite server
        run: npm run dev &

      - name: Run Cypress tests
        run: npm run test:cypress -- --exit || echo "Cypress tests failed with exit code $?"

      # - name: Generate Mochawesome Report
      #   run: npx cypress run --config baseUrl=http://localhost:5173

      - name: Archive Mochawesome Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: cypress/reports

      - name: Send Email with Mochawesome Report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: 'smtp.gmail.com'
          server_port: '587'
          username: 'reportcypress'
          password: 'K8NbZegNxtYnuLcEAoi9'
          subject: 'Cypress Test Report'
          from: 'reportcypress@gmail.com'
          to: 'ariful.rony10@gmail.com'
          body: 'Please find the attached Mochawesome test report.'
          attachments: 'cypress/reports/mochawesome-report/mochawesome.json'
          content_type: 'text/plain'
