name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Start Vite server
        run: npm run dev &

      - name: Run Cypress tests and Generate Mochawesome Report
        run: |
          npx cypress run --config baseUrl=http://localhost:5173
          export CYPRESS_EXIT_CODE=$?

      - name: Send Email with Mochawesome Report
        if: ${{ env.CYPRESS_EXIT_CODE == '0' || env.CYPRESS_EXIT_CODE == '1' }}
        run: |
          echo "Sending email with Mochawesome report..."

          # Install nodemailer
          npm install nodemailer

          # Create a Node.js script to send the email
          node -e "const nodemailer = require('nodemailer');
            const transporter = nodemailer.createTransport({
              host: 'smtp-mail.outlook.com',
              port: 587,
              secure: false, // true for 465, false for other ports
              auth: {
                user: 'githubreport@outlook.com',
                pass: "'kq'x;u@!n94'sg6W8T`",
              },
            });
            transporter.sendMail({
              from: 'githubreport@outlook.com',
              to: 'ariful.rony10@gmail.com',
              subject: 'Cypress Test Report',
              text: 'Please find the attached Mochawesome test report.',
              attachments: [{ path: 'cypress/reports/mochawesome-report/mochawesome.json' }],
            }, (error, info) => {
              if (error) {
                console.error(error);
              } else {
                console.log('Email sent: ' + info.response);
              }
            });"

      # Optional: Archive Mochawesome Report (consider security implications)
      # - name: Archive Mochawesome Report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: mochawesome-report
      #     path: cypress/

      - name: Exit Code
        run: exit $CYPRESS_EXIT_CODE
